//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.17.1
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace eshoppgsoftweb.lib.Models.UmbracoCmsContent
{
	/// <summary>LandingPage</summary>
	[PublishedModel("landingPage")]
	public partial class LandingPage : PublishedContentModel, ICmsContent, ISEO
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		public new const string ModelTypeAlias = "landingPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LandingPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public LandingPage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// GridContent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		[ImplementPropertyType("gridContent")]
		public virtual decimal GridContent => global::eshoppgsoftweb.lib.Models.UmbracoCmsContent.CmsContent.GetGridContent(this);

		///<summary>
		/// Menu Title: Názov stránky pre menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		[ImplementPropertyType("menuTitle")]
		public virtual string MenuTitle => global::eshoppgsoftweb.lib.Models.UmbracoCmsContent.SEO.GetMenuTitle(this);

		///<summary>
		/// Meta Description: Popis stránky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::eshoppgsoftweb.lib.Models.UmbracoCmsContent.SEO.GetMetaDescription(this);

		///<summary>
		/// Page Title: Názov stránky
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::eshoppgsoftweb.lib.Models.UmbracoCmsContent.SEO.GetPageTitle(this);

		///<summary>
		/// UmbracoNaviHide: Ak je táto voľba zaškrtnutá, potom daná stránka nebude súčasťou menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.17.1")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::eshoppgsoftweb.lib.Models.UmbracoCmsContent.SEO.GetUmbracoNaviHide(this);
	}
}
